
services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: ${DB_USER:-postgres} 
      POSTGRES_PASSWORD: ${DB_PASSWORD:-senha_segura} 
      POSTGRES_DB: ${DB_NAME:-docmanager_db}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER:-postgres} -d ${DB_NAME:-docmanager_db}"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: "postgresql://${DB_USER:-postgres}:${DB_PASSWORD:-senha_segura}@db:5432/${DB_NAME:-docmanager_db}?schema=public"
      JWT_SECRET: ${JWT_SECRET:-default_secret_altere_em_producao}  # Nunca coloque a chave real aqui!
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./uploads:/app/uploads
      - .:/app

volumes:
  postgres_data: